### ISSUE TITLE
Problem with MFI Controller

### ISSUE THREAD

**Issue by amingomezd** [tomkidd/DOOM3-iOS#3]
Hi, thanks for the port of the game. i have the following problem with the nimbus steelseries controller and the apple tv 4k, i have downloaded the steam game and copy the base folder, then compile and install to the apple tv:

[https://www.youtube.com/watch?v=Jj7uA2SVm54](https://www.youtube.com/watch?v=Jj7uA2SVm54)

as you can see the controller movement is unresponsive. I 've tried the controller in other aptv games, and it works just fine. Can you please help me with this?

**Comment by dnicolson** [comment]
The problem only exists on tvOS, on iOS the controller seems to work properly.
